# spring.profiles.active=local
spring:
  cassandra:
    contact-points: 127.0.0.1 #127.0.0.1 cassandra
    port: 9042
    keyspace-name: my_keyspace
    local-datacenter: datacenter1
    schema-action: none #CREATE_IF_NOT_EXISTS
