spring:
  application:
    name: ticket-system
  profiles:
    active: prod
  server:
    port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ticket.ticket_system.entity
  configuration:
    map-underscore-to-camel-case: true
management:
  server:
    port: 8081
    base-path: /management
  endpoints:
    web:
      exposure:
        include: "*" # health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true
    export:
      prometheus:
        enabled: true
  health:
    db:
      enabled: true
  logging:
    level:
      org.springframework: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
