spring:
  cassandra:
    contact-points: cassandra-1729401233.default.svc.cluster.local
    port: 9042
    keyspace-name: my_keyspace
    local-datacenter: datacenter1
    schema-action: none
    username: cassandra
    password: ZOJd966yft
