spring:
  application:
    name: ticket-system
  profiles:
    active: prod
  server:
    port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket_system?useSSL=false&serverTimezone=UTC
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ticket_system?useSSL=false&serverTimezone=UTC}
    username: root
    password: 1234
  data:
    redis:
      host: localhost
#      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      database: 0
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ticket-purchase-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.ticket.ticket_system.model
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ticket.ticket_system.entity
  configuration:
    map-underscore-to-camel-case: true
management:
  server:
    port: 8081
    base-path: /management
  endpoints:
    web:
      exposure:
        include: "*" # health, info, metrics
      base-path: /actuator
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true
    export:
      prometheus:
        enabled: true
#    tags:
#      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo:
        http:
          server:
            requests: 10ms, 50ms, 100ms, 200ms, 500ms
  health:
    db:
      enabled: true
  logging:
    level:
      org.springframework: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
