spring:
  application:
    name: ticket-system
  profiles:
    active: prod
  server:
    port: 8080
management:
  server:
    port: 8081
    base-path: /management
  endpoints:
    web:
      exposure:
        include: "*" # health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true
    export:
      prometheus:
        enabled: true
  health:
    cassandra:
      enabled: true
  logging:
    level:
      org.springframework: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
